; [pytest]
; addopts = -v --headed --browser chromium
; testpaths = tests
; markers =
;     smoke: Smoke test cases
;     regression: Regression test cases
;     appointment: Appointment test cases
;     auth: Login/logout test cases

[pytest]
testpaths = tests
pythonpath = .
addopts = -v --headed --browser chromium
markers =
    smoke: Smoke test cases
    regression: Regression test cases
    appointment: Appointment test cases
    auth: Login/logout test cases