import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://scale.jaldee.com/business/login?v=2.4.607")
    page.get_by_role("textbox", name="Enter Login ID").click()
    page.get_by_role("textbox", name="Enter Login ID").fill("40251")
    page.get_by_role("textbox", name="Enter Login ID").press("Tab")
    page.get_by_role("textbox", name="Enter password").fill("Jaldee01")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("link").nth(3).click()
    page.locator("div:nth-child(2) > div > div > #actionNav_IP_DBoard > .dashboard-card-image > img").click()
    page.get_by_role("button", name="add New Admission").click()
    page.get_by_role("button", name="  Create Patient").click()
    page.get_by_role("textbox", name="Enter First Name").click()
    page.get_by_role("textbox", name="Enter First Name").fill("Kavya")
    page.get_by_role("textbox", name="Enter First Name").press("Tab")
    page.get_by_role("textbox", name="Enter Last Name").fill("M")
    page.get_by_role("textbox", name="Enter Last Name").press("Tab")
    page.get_by_role("textbox", name="Enter Email Id").fill("kavya.test@jaldee.com")
    page.get_by_role("textbox", name="10123").first.click()
    page.get_by_role("textbox", name="10123").first.fill("5555808080")
    page.get_by_text("Select Gender").click()
    page.get_by_role("option", name="Female").click()
    page.get_by_role("button", name="Save & Next").click()
    page.locator("p-dropdown").filter(has_text="Admis-Ren1148").get_by_label("dropdown trigger").click()
    page.get_by_role("textbox", name="Select Expected Checkout Date").click()
    page.locator("p-dropdown").filter(has_text="Select Admitted Doctor").get_by_label("dropdown trigger").click()
    page.get_by_role("option", name="Vijay Kumar").click()
    page.get_by_role("button").nth(3).click()
    page.get_by_role("table").get_by_text("3", exact=True).click()
    page.get_by_role("button").nth(4).click()
    page.get_by_role("table").get_by_text("7", exact=True).click()
    page.get_by_text("Bed158B Normal").click()
    page.get_by_role("button", name="Admit Now").click()
    page.get_by_role("row", name="RE000904 K Kavya M #Id : 1026").locator("#btnViewIp_IP_IpGrd").click()
    page.get_by_role("button", name="   Service").click()
    page.get_by_role("searchbox", name="Search Service").click()
    page.get_by_role("searchbox", name="Search Service").fill("nur")
    page.get_by_role("option", name="nursing service").click()
    page.get_by_role("button", name="Add Service").click()
    page.get_by_role("button").filter(has_text="•••").click()
    page.get_by_role("menuitem", name="  Request Order").click()
    page.get_by_role("button", name="Item").click()
    page.get_by_label("", exact=True).check()
    page.locator("#btnSubmitItems_ORD_ItemSelectionTop").click()
    page.get_by_role("button", name="Increase itemQuantity").click()
    page.get_by_role("button", name="Request Order").click()
    page.get_by_text("Veliyannur").click()
    page.get_by_role("button", name="Select").click()
    page.get_by_role("link").nth(4).click()
    page.locator("div:nth-child(3) > #actionRouteTo_ORD_Dashbrd > .p-element > .p-card > .p-card-body > .p-card-content > div > div > img").click()
    page.get_by_role("row", name="03/07/2026 00091   Order").locator("#btnACPTOrd_ORD_RQTORD").click()
    page.get_by_role("button", name="Confirm Order").click()
    page.get_by_role("button", name="Create Invoice").click()
    page.get_by_role("button", name="View Invoice").click()
    page.get_by_role("link").nth(3).click()
    page.get_by_text("Inpatients", exact=True).click()
    page.get_by_role("row", name="RE000904 K Kavya M #Id : 1026").locator("#btnViewIp_IP_IpGrd").click()
    page.locator("a").filter(has_text="Invoices").click()
    page.get_by_role("button", name="  Create").click()
    page.get_by_role("menuitem", name="settings  New Invoice").click()
    page.get_by_role("button", name="Generate").click()
    page.get_by_role("button", name="Generate Invoice").click()
    page.get_by_role("heading", name="   Invoice Details").locator("i").click()
    page.locator(".p-datatable-header").click()
    page.get_by_role("button", name="  Create").click()
    page.get_by_role("menuitem", name="settings  Master Invoice").click()
    page.get_by_role("row", name="Id & Date Total Amount (  )").get_by_label("").check()
    page.get_by_role("button", name="  Link & Generate Master").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_role("link").nth(4).click()
    page.get_by_text("Requests").first.click()
    page.get_by_role("row", name="03/07/2026 00091   Order").locator("#btnACPTOrd_ORD_RQTORD").click()
    page.get_by_role("button", name="View Order").click()
    page.get_by_role("button", name="Complete Order").click()
    page.get_by_role("link").nth(3).click()
    page.get_by_text("Inpatients", exact=True).click()
    page.get_by_role("row", name="RE000904 K Kavya M #Id : 1026").locator("#btnViewIp_IP_IpGrd").click()
    page.get_by_role("button", name="  Create").click()
    page.get_by_role("menuitem", name="settings  Master Invoice").click()
    page.get_by_role("row", name="Id & Date Total Amount (  )").get_by_label("").check()
    page.get_by_role("button", name="  Link & Generate Master").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_role("button", name="View").nth(1).click()
    page.get_by_text("V", exact=True).click()
    page.get_by_text("Sign Out").click()
