import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://scale.jaldee.com/business/login?v=2.4.626")
    page.get_by_role("textbox", name="Enter Login ID").click()
    page.get_by_role("textbox", name="Enter Login ID").fill("5555556030")
    page.get_by_role("textbox", name="Enter Login ID").press("Tab")
    page.get_by_role("textbox", name="Enter password").fill("Jaldee01")
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("link").nth(1).click()
    page.locator("p-card").filter(has_text=re.compile(r"^Appointment$")).click()
    page.locator("#btnCreateCust_BUS_appt").click()
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").fill("Thanvi")
    page.get_by_role("textbox", name="First Name").press("Tab")
    page.get_by_role("textbox", name="Last Name").fill("Ramesh")
    page.get_by_role("textbox", name="Last Name").press("Tab")
    page.get_by_role("textbox", name="Patient ID").press("Tab")
    page.get_by_role("textbox", name="Email(user@xyz.com)").fill("thanvi.test@jaldee.com")
    page.get_by_role("textbox", name="10123").nth(1).click()
    page.get_by_role("textbox", name="10123").nth(1).fill("5550002356")
    page.get_by_role("radio", name="Female").check()
    page.get_by_role("button", name="Save").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_text("Hari Kumar").click()
    page.get_by_role("option", name="Naveen KP").click()
    page.locator("#selectService_BUS_apptForm").get_by_role("button", name="dropdown trigger").click()
    page.get_by_text("Video call Services").click()
    page.get_by_role("button", name="Confirm").click()
    page.get_by_role("tab", name="Thanvi Ramesh 12:10 PM 24/07/").click()
    page.get_by_role("button", name="Assign Myself View Details").click()
    page.get_by_role("button", name="Generate BillCreate Invoice").click()
    page.get_by_role("button", name="Update").click()
    page.get_by_role("heading", name="   Back").locator("i").click()
    page.get_by_role("button", name="Generate BillNew Invoice").click()
    page.get_by_role("button", name="E Add Procedure/Item").click()
    page.get_by_role("option", name="Consultation", exact=True).click()
    page.get_by_role("button", name="Add", exact=True).click()
    page.get_by_role("button", name="Update").click()
    page.get_by_role("heading", name="   Back").locator("i").click()
    page.locator("a").filter(has_text="Invoices").click()
    page.get_by_role("button", name="  Create Invoice").click()
    page.get_by_role("menuitem", name="settings  Master Invoice").click()
    page.get_by_role("row", name="ID Date Amount  (  ) Amount").get_by_label("").check()
    page.get_by_role("button", name="  Link & Generate Master").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_role("button", name="View").nth(2).click()
    page.get_by_role("button", name="dropdown trigger").click()
    page.get_by_text("Pay by Others").click()
    page.get_by_text("UPI").click()
    page.get_by_text("Credit Card").click()
    page.locator("textarea").click()
    page.locator("textarea").fill("nj")
    page.get_by_role("button", name="Pay").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_text("V", exact=True).click()
    page.get_by_text("Sign Out").click()
