import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://scale.jaldee.com/business/login?v=2.4.587")
    page.get_by_role("textbox", name="Enter Login ID").click()
    page.get_by_role("textbox", name="Enter Login ID").fill("40251")
    page.get_by_role("textbox", name="Enter Login ID").press("Tab")
    page.get_by_role("textbox", name="Enter password").fill("Jaldee01")
    page.locator("form").get_by_role("button").filter(has_text=re.compile(r"^$")).click()
    page.get_by_role("button", name="Sign In").click()
    page.get_by_role("link").nth(3).click()
    page.goto("https://scale.jaldee.com/business/ip/dashboard?v=2.4.587&p_source=p_sidebar")
    page.locator("div:nth-child(2) > div > div > #actionNav_IP_DBoard > .dashboard-card-image > img").click()
    page.get_by_role("button", name="add New Admission").click()
    page.get_by_role("button", name="  Create Patient").click()
    page.get_by_role("textbox", name="Enter First Name").click()
    page.get_by_role("textbox", name="Enter First Name").fill("Rima")
    page.get_by_role("textbox", name="Enter First Name").press("Tab")
    page.get_by_role("textbox", name="Enter Last Name").fill("K")
    page.get_by_role("textbox", name="Enter Email Id").click()
    page.get_by_role("textbox", name="Enter Email Id").fill("rima.test@jaldee.com")
    page.get_by_role("textbox", name="10123").first.click()
    page.get_by_role("textbox", name="10123").first.fill("5550002145")
    page.get_by_text("Select Gender").click()
    page.get_by_text("Female").click()
    page.get_by_role("textbox", name="Enter Address").click()
    page.get_by_role("textbox", name="Enter Address").fill("fytuyi")
    page.get_by_role("button", name="Save & Next").click()
    page.locator("p-dropdown").filter(has_text="Select Admitted Doctor").get_by_label("dropdown trigger").click()
    page.get_by_role("option", name="Vijay Kumar").click()
    page.get_by_role("button").nth(4).click()
    page.get_by_text("23", exact=True).click()
    page.get_by_role("button").nth(5).click()
    page.get_by_text("24", exact=True).click()
    page.get_by_role("textbox", name="Please provide any additional").click()
    page.get_by_role("textbox", name="Please provide any additional").fill("detret")
    page.get_by_text("Block D 1st floor").nth(1).click()
    page.get_by_role("button", name="Admit Now").click()
    page.get_by_role("row", name="RE000766 R Rima K #Id : 849").locator("#btnViewIp_IP_IpGrd").click()
    page.get_by_role("button", name="   Service").click()
    page.get_by_role("searchbox", name="Search Service").click()
    page.get_by_role("searchbox", name="Search Service").fill("d")
    page.get_by_role("option", name="Doc Visit").click()
    page.get_by_role("button", name="Add Service").click()
    page.locator("#btnServiceActionMenu_IP_AD_DE_New_ip_ser_con_det_84bd849d-cf64-4eb9-a087-2e275f676e59").click()
    page.get_by_role("menuitem", name="  Request Order").click()
    page.get_by_role("button", name="Item").click()
    page.get_by_role("row", name="Med_2 Enable").locator("#SelectItem_ORD_ItemSelection-input").check()
    page.locator("#btnSubmitItems_ORD_ItemSelectionTop").click()
    page.get_by_role("button", name="Increase itemQuantity").click()
    page.get_by_role("button", name="Request Order").click()
    page.get_by_text("Swathi Medical Veliyannur").click()
    page.get_by_role("button", name="Select").click()
    page.get_by_role("link").nth(4).click()
    page.locator("div:nth-child(3) > #actionRouteTo_ORD_Dashbrd > .p-element > .p-card > .p-card-body > .p-card-content > div > div > img").click()
    page.get_by_role("row", name="23/06/2026 00043   Order Rima").locator("#btnACPTOrd_ORD_RQTORD").click()
    page.get_by_role("button", name="Confirm Order").click()
    page.get_by_role("button", name="Create Invoice").click()
    page.get_by_role("button", name="View Invoice").click()
    page.get_by_role("link").nth(3).click()
    page.goto("https://scale.jaldee.com/business/ip/dashboard?v=2.4.587&p_source=p_sidebar")
    page.locator("#actionNav_IP_DBoard").nth(1).click()
    page.get_by_role("row", name="RE000766 R Rima K #Id : 849").locator("#btnViewIp_IP_IpGrd").click()
    page.locator("a").filter(has_text="Invoices").click()
    page.get_by_role("button", name="  Create").click()
    page.get_by_role("menuitem", name="settings  New Invoice").click()
    page.get_by_role("button", name="Generate").click()
    page.get_by_role("button", name="Generate Invoice").click()
    page.get_by_role("heading", name="   Invoice Details").locator("i").click()
    page.get_by_role("button", name="  Create").click()
    page.get_by_role("menuitem", name="settings  Master Invoice").click()
    page.get_by_role("row", name="#3 Jun 23, 2026 849.00 849.00").get_by_label("").check()
    page.get_by_role("row", name="#IN443 Jun 23, 2026 350.00").get_by_label("").check()
    page.get_by_role("button", name="  Link & Generate Master").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_role("button", name="View").nth(1).click()
    page.get_by_role("button", name=" Edit").click()
    page.locator("#btnRowMenu_Pharm_IP_Invoice").click()
    page.get_by_role("menuitem", name="Apply Discount").click()
    page.locator("#slctItemDiscount_IP_Invoice").select_option("34906")
    page.get_by_role("textbox", name="Number").click()
    page.get_by_role("textbox", name="Number").fill("30")
    page.get_by_role("button", name="Apply").click()
    page.locator("#btnRowMenu_Pharm_IP_Invoice").click()
    page.get_by_role("menuitem", name="Remove Discount").click()
    page.get_by_role("button", name="View Invoice").click()
    page.locator("form").get_by_role("button", name="dropdown trigger").click()
    page.get_by_text("Pay by Cash").click()
    page.locator("textarea").click()
    page.locator("textarea").fill("scdssfd")
    page.get_by_role("button", name="Pay").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_role("heading", name="   Invoice Details").locator("i").click()
    page.locator("#spnBack_IP_Invoice i").click()
    page.get_by_role("link").nth(3).click()
    page.goto("https://scale.jaldee.com/business/ip/dashboard?v=2.4.587&p_source=p_sidebar")
    page.get_by_text("Inpatients", exact=True).click()
    page.get_by_role("row", name="RE000766 R Rima K #Id : 849").locator("#btnSts_IP_IpGrd").click()
    page.locator(".cdk-overlay-backdrop").click()
    page.get_by_role("row", name="RE000766 R Rima K #Id : 849").locator("#btnViewIp_IP_IpGrd").click()
    page.get_by_role("button", name="Discharge").click()
    page.get_by_role("button", name="Use Template").first.click()
    page.get_by_role("button", name="Use template").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_role("button", name="Discharge").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_role("button", name=" Checkout").click()
    page.get_by_role("button", name="Checkout").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_role("button", name="  Create").click()
    page.get_by_role("menuitem", name="settings  New Invoice").click()
    page.get_by_role("button", name="Generate").click()
    page.get_by_role("button", name="Generate Invoice").click()
    page.locator("form").get_by_role("button", name="dropdown trigger").click()
    page.locator("p-dropdownitem:nth-child(2) > .p-ripple > .dropdown-item").click()
    page.get_by_role("button", name="Pay").click()
    page.get_by_role("button", name="Yes").click()
    page.locator("#actionBack_IP_InvView").click()
    page.get_by_role("button", name=" Checkout").click()
    page.get_by_role("button", name="Checkout").click()
    page.get_by_role("button", name="Yes").click()
    page.get_by_role("alert").get_by_role("button").click()
    page.get_by_text("V", exact=True).click()
    page.get_by_text("Sign Out").click()
